In [3]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

In [4]:
X , y = load_breast_cancer(return_X_y=True)
X.shape

(569, 30)

In [14]:
X_train , X_test , y_train , y_test = train_test_split(X , y , random_state=True , test_size=0.3)

In [6]:
X_train.shape

(398, 30)

In [7]:
knn = KNeighborsClassifier(n_neighbors=3)

In [8]:
scale = StandardScaler()

X_train_scale = scale.fit_transform(X_train)
X_test_scale = scale.transform(X_test)

In [9]:
knn.fit(X_train_scale , y_train)

KNeighborsClassifier(n_neighbors=3)

In [10]:
knn.score(X_test_scale , y_test)

0.9649122807017544

In [11]:
scores = {}
for i in range(1 , 16):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train_scale , y_train)
    score = knn.score(X_test_scale , y_test)
    scores[i-1] = {f"K-val: {i} {","} score: {score}"}

scores

{0: {'K-val: 1 , score: 0.9590643274853801'},
 1: {'K-val: 2 , score: 0.9707602339181286'},
 2: {'K-val: 3 , score: 0.9649122807017544'},
 3: {'K-val: 4 , score: 0.9473684210526315'},
 4: {'K-val: 5 , score: 0.9590643274853801'},
 5: {'K-val: 6 , score: 0.9532163742690059'},
 6: {'K-val: 7 , score: 0.9590643274853801'},
 7: {'K-val: 8 , score: 0.9532163742690059'},
 8: {'K-val: 9 , score: 0.9649122807017544'},
 9: {'K-val: 10 , score: 0.9590643274853801'},
 10: {'K-val: 11 , score: 0.9649122807017544'},
 11: {'K-val: 12 , score: 0.9532163742690059'},
 12: {'K-val: 13 , score: 0.9649122807017544'},
 13: {'K-val: 14 , score: 0.9590643274853801'},
 14: {'K-val: 15 , score: 0.9649122807017544'}}

In [12]:
val_list = []
for key, val_set in scores.items():
    val_str = list(val_set)[0]  
    score_num = float(val_str.split('score: ')[1]) 
    val_list.append(float((list(val_set)[0].split("score: ")[1])))

print(max(val_list))

0.9707602339181286


In [60]:
import numpy as np

class knn:
    def __init__(self , k):
        self.k = k
        self.X_train = None
        self.y_train = None

    def fit(self , X , y):
        self.X_train = X
        self.y_train = y

    def _euclidean_dist(self , x1 , x2):
        distance = np.sqrt(np.sum((x1 - x2)**2))
        return distance

    def predict(self , X):
        predictions = [self._predict(x) for x in X]
        return predictions

    def _predict(self , x):
        distance = [self._euclidean_dist(x , x_train) for x_train in self.X_train]

        ##Nearest k
        k_indices = np.argsort(distance)[0:self.k]
        #k_nearest_labels = [self.y_train[i] for i in k_indices]
        return k_indices
        

In [61]:
k1 = knn(3)

In [62]:
k1.fit(X_train_scale , y_train)

In [63]:
k1.predict(X_test_scale)

[array([ 83, 343,  29], dtype=int64),
 array([ 26, 359, 381], dtype=int64),
 array([165, 267, 146], dtype=int64),
 array([152, 239, 368], dtype=int64),
 array([362, 328,  94], dtype=int64),
 array([ 27, 262, 108], dtype=int64),
 array([288,  82, 341], dtype=int64),
 array([ 78, 135, 312], dtype=int64),
 array([323,  60, 299], dtype=int64),
 array([113, 289, 371], dtype=int64),
 array([178,   0, 270], dtype=int64),
 array([200, 322, 295], dtype=int64),
 array([213, 186, 290], dtype=int64),
 array([360, 363,  89], dtype=int64),
 array([362,  16,  70], dtype=int64),
 array([ 11, 298,  44], dtype=int64),
 array([326, 168,  89], dtype=int64),
 array([146,   0, 361], dtype=int64),
 array([193, 117,  12], dtype=int64),
 array([156,  66,  78], dtype=int64),
 array([178,  28, 326], dtype=int64),
 array([ 61, 342,  50], dtype=int64),
 array([ 82, 227, 156], dtype=int64),
 array([ 44, 297, 146], dtype=int64),
 array([ 27, 353, 290], dtype=int64),
 array([ 21, 321, 153], dtype=int64),
 array([  2,

In [67]:
k1.y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,